---
title: "Plots in A Paper Submitted for AIIT Bulletin (14)"
output: html_notebook
---

# libraries

ライブラリをロード

```{r echo=FALSE, message=FALSE, results='hide'}
library(tidyverse)
library(googlesheets4)
library(lubridate)
library(fontregisterer)
library(ggridges)
library(ggrepel)
library(sf) # for anthro map
library(rnaturalearth) # for anthro map
library(rnaturalearthdata) # for anthro map
library(MASS) # corresp analysis for sak
library(ape) # https://www1.doshisha.ac.jp/~mjin/R/Chap_28/28.html
# library(poppr) # https://grunwaldlab.github.io/poppr/reference/upgma.html
library(ggdendro) # https://cran.r-project.org/web/packages/ggdendro/vignettes/ggdendro.html
library(factoextra) # fviz_cluster

```

```{r}
setwd("~/Documents/phylogen")
theme_set(theme(text = element_text(family = "YuGothic")))
knitr::opts_chunk$set(dev = "ragg_png")
```


# data

データは[Google Spreadsheets](https://docs.google.com/spreadsheets/d/1VZzjCMs21iBTIXoHR2Ph8wqyS8jQBlS4TDAmJXYjVKI/edit?usp=sharing)に格納している。データの各所が「どうしてこうなっているか」を忘れている部分があるが、仕方ない。なんとかしたい。

```{r}
data_sak_raw <- read_sheet("https://docs.google.com/spreadsheets/d/1VZzjCMs21iBTIXoHR2Ph8wqyS8jQBlS4TDAmJXYjVKI/edit?usp=sharing", sheet = "swiss army knives")
data_idol_raw <- read_sheet("https://docs.google.com/spreadsheets/d/1VZzjCMs21iBTIXoHR2Ph8wqyS8jQBlS4TDAmJXYjVKI/edit?usp=sharing", sheet = "idol lightsticks")
data_anth_raw <- read_sheet("https://docs.google.com/spreadsheets/d/1VZzjCMs21iBTIXoHR2Ph8wqyS8jQBlS4TDAmJXYjVKI/edit?usp=sharing", sheet = "anthropomorphic artefacts", skip = 1)
```

# idol

## dataframe

グループ名から年・月を復元する。ピリオドで分けたい場合は`"[.]"`を使う。外群などは1996には出現していたので開始年である1996とした。グループ名のリコードなども一気に行う。

```{r}
df_idol <- data_idol_raw |> 
  separate(ID, c("group", "year", "month"),
           sep = "[.]") |> 
  mutate_if(is.character, list(~na_if(., ""))) |> 
  replace_na(list(year = "1996", month = "1")) |>
  mutate(
    year = as.numeric(year),
      month = as.numeric(month),
      date = ym(paste0(year, "-", month)),
      group = recode(
        group, 
        smap = "SMAP",
        Kinki = "KinKi Kids", 
        Taki = "タッキー＆翼",
        arashi = "嵐",
        eito = "関ジャニ∞",
        News = "NEWS",
        `kat-tun` = "KAT-TUN",
        jump = "Hey! Say! JUMP", 
        sexyzone = "Sexy Zone",
        `abc-z` = "A.B.C-Z",
        kismy = "Kis-My-Ft2",
        Jr = "ジャニーズJr.",
        common = "事務所共通",
        yuudoubou = "outgroup_誘導棒",
        KingBlade = "outgroup_キングブレード",
        Twice = "outgroup_TWICE")
       ) 
```

## plot chronology

[reorder](https://www.r-graph-gallery.com/267-reorder-a-variable-in-ggplot2.html)

```{r message=FALSE, warning=FALSE}
df_idol_chronology <- df_idol |> 
  filter(!str_detect(group, "outgroup")) |> 
  mutate(group = factor(group))
  
chronology <- df_idol_chronology |> 
  mutate(group = fct_reorder(group, date, min)) |> 
  ggplot(aes(x = date, y = group)) +
  geom_density_ridges_gradient(
    aes(fill = stat(x)),
    scale = 0.8,
    rel_min_height = 0.03,
    jittered_points = TRUE,
    position = position_points_jitter(width = 0.05, height = 0),
    point_shape = '|', point_size = 3, point_alpha = 1, alpha = 0.2) +
  scale_fill_viridis_c(limits = c(ym("1995-1"), ym("2018-1"))) +
  coord_cartesian(xlim = c(ym("1996-1"), ym("2017-1"))) +
  xlab("発売年") +
  theme_bw(base_family = "YuGothic" ) +
  theme(legend.position = "none") 

chronology
```

### save chronology
```{r, dev="ragg_png"}
chronology |> 
  ggsave(filename = "output/chronology.pdf", 
         device = cairo_pdf,
         dpi = 450,
         unit = "mm",
       height = 50*1.3 , # pixelsでのサイズ
       width = 75*1.3,  # pixelsでのサイズ
       limitsize = FALSE)
```


# anthropomorphic

```{r}
df_anth <- data_anth_raw |> 
  separate(col = `approximate geocode`, into = c("latitude", "longitude"), sep = ",\\s")
df_anth
```
## data

[sf with points](https://gist.github.com/andrewheiss/0580d6ffec37b6bc4d0ae8e77bf30956)

```{r}
this_year <- 2021
anth_sf <- df_anth |> 
  filter(!is.na(longitude)) |> 
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326) |> 
  st_transform(crs = 4326) |> 
  st_coordinates() # converted coordinates of X and Y
df_anth2 <- bind_cols(df_anth |> filter(!is.na(longitude)), anth_sf |> as_tibble())

df_anth3<- df_anth2 |> 
  mutate(year_d_upper = this_year - year_upper,
         year_d_lower = this_year - year_lower,
         year =  if_else(is.na(year), (year_lower + year_upper) / 2, year),
         d = this_year - year,
         name_alt_short = factor(name_alt_short)
  ) |>
  mutate(name_alt_short = fct_reorder(name_alt_short, year, min))
```


## plot chronology

```{r}
df_anth3 |> 
  ggplot(aes(y = name_alt_short, x = d, xmax = year_d_upper, xmin = year_d_lower)) +
  geom_point() +
  geom_linerange() +
  scale_x_continuous(trans = "log10")
```

## map ~ time

```{r fig.width = 5, fig.height=2.3}
library(fontregisterer)
world <- ne_countries(scale = "medium", returnclass = "sf" )
ggplot(data = world) +
  geom_sf(data = world, fill = "gray99") +
  geom_point(data = df_anth3, aes(x = X, y = Y, fill = d), size = 1, pch = 21) +
  geom_label_repel(
    data = df_anth3, 
    aes(x = X, y = Y, label = name_alt_short, fill = d), 
    max.overlaps = 30, 
    min.segment.length = .3,
    size = 2.5,
    family = "Fira Code",
    colour = "white",
    fontface = "bold", # not working?
    segment.color = "black"
    ) +
  scale_fill_viridis_c(trans = "log10", direction = -1) +
  scale_y_continuous(breaks = seq(-180, 180, by = 30), limits = c(-10, 80)) +
  scale_x_continuous(breaks = seq(180, -180, by = -60), limits = c(-150, 150)) +
  coord_sf(expand = FALSE) +
  theme_grey(base_family = "Fira Code") +
  xlab("longitude") +
  ylab("latitude") +
  guides(fill = guide_colourbar(barwidth = 7, barheight = .5), direction = "horizontal") +
  theme(legend.direction = "horizontal", legend.position = c(0.85, 0.9))


ggsave(filename = "output/anth_map.pdf", 
         device = cairo_pdf,
         dpi = 300,
         unit = "mm",
       height = 80 , # pixelsでのサイズ
       width = 200,  # pixelsでのサイズ
       limitsize = FALSE)
```



# sak

## overview

```{r}
df_sak <- data_sak_raw |> 
  mutate(id = paste0(class, short_name)) 
df_sak |> 
  filter(Price <30000, class < 112) |> 
  ggplot(aes(x = Price, y = Functions, colour = class, group = class)) +
  geom_point() +
  geom_smooth(method = "lm") 
  # facet_grid(cols = vars(class))
```

```{r}
df_sak |> 
  filter(Price <30000, class < 112) |> 
  ggplot(aes(x = width, y = Price, colour = weight)) +
  geom_point() +
  facet_grid(cols = vars(class))
```

## corresp


data
https://www1.doshisha.ac.jp/~mjin/R/Chap_26/26.html

```{r fig.width=5, figh.height = 3}
df_sak_corresp <- df_sak |> 
  filter(Price < 30000) |> # remove swissChampXAVT
  select(Lock:DualDensityScales) |> 
  mutate(across(everything(), as.factor))
sak_mca <- mca(df_sak_corresp)

sak_mca |> summary()

df_sak_mca_rs <- sak_mca$rs |>
  as_tibble() |> 
  transmute(mca_x = `1`, mca_y = `2`)
df_sak_corresp2 <- bind_cols(df_sak |> filter(Price < 30000), df_sak_mca_rs)
```


#### all corresp

```{r}
df_sak_corresp2 |>
  ggplot(aes(mca_x *1e5, mca_y * 1e5, label = short_name, colour = class)) +
  geom_point(data = df_sak_corresp2 |> select(-class), colour = "grey70") +
  geom_point(aes(size = Price)) +
  geom_text_repel(
    # force = .3,
    # force_pull = .5,
    max.overlaps = 10, 
    max.time = 3, 
    max.iter = 3e5, 
    size = 2, 
    min.segment.length = .1, 
    family = "Fira Code"
    ) +
  scale_colour_viridis_c() +
  scale_size_area() +
  # labs(colour = "Price (1k yen)" ) +
  xlab("Dimension 1") +
  ylab("Dimension 2") +
  theme_minimal(base_family = "Fira Code") +
  theme(panel.background = element_rect(fill = "white", colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  guides(colour = guide_colourbar(barwidth = 5, barheight = .5), direction = "horizontal") +
  theme(legend.direction = "horizontal", legend.position = "bottom")
ggsave(filename = "output/sak_correspXY_all.pdf", 
         device = cairo_pdf,
         dpi = 300,
         unit = "mm",
       height = 100 , # pixelsでのサイズ
       width = 150,  # pixelsでのサイズ
       limitsize = FALSE)
```



#### facet grid
```{r fig.width=5, figh.height = 3}
df_sak_corresp2 |>
  ggplot(aes(mca_x, mca_y, label = short_name, colour = Price / 1000)) +
  geom_point(data = df_sak_corresp2 |> select(-class), colour = "grey70") +
    geom_point() +
  geom_text_repel(
    # force = .3,
    # force_pull = .5,
    max.overlaps = 50, 
    max.time = 3, 
    max.iter = 3e5, 
    size = 2, 
    min.segment.length = .1, 
    family = "Fira Code"
    ) +
  scale_colour_viridis_c() +
  labs(colour = "Price (1k yen)" ) +
  xlab("Dimension 1") +
  ylab("Dimension 2") +
  facet_wrap(vars(class)) +
  theme_minimal(base_family = "Fira Code") +
  theme(panel.background = element_rect(fill = "white", colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  guides(colour = guide_colourbar(barwidth = 5, barheight = .5), direction = "horizontal") +
  theme(legend.direction = "horizontal", legend.position = "bottom")

ggsave(filename = "output/sak_correspXY.pdf", 
         device = cairo_pdf,
         dpi = 300,
         unit = "mm",
       height = 150 , # pixelsでのサイズ
       width = 200,  # pixelsでのサイズ
       limitsize = FALSE)
```



### compare with cluster analysis

```{r}
sak_upgma_cluster <- dist(df_sak_corresp) |>
  hclust(method = "average")  # average = UPGMA https://stat.ethz.ch/R-manual/R-devel/library/stats/html/hclust.html
sak_upgma_tree <- sak_upgma_cluster |> 
  as.dendrogram() |> 
  dendro_data(type = "rectangle")
sak_upgma_tree$labels$label <-   df_sak_corresp2$short_name

ggplot() +
  geom_segment(data = sak_upgma_tree$segment, aes(x, y, xend = xend, yend = yend)) + 
  coord_flip() + 
  geom_text(data = sak_upgma_tree$label, aes(x, y, label = label), hjust = 0, nudge_y = .05, size = 2, family = "Fira Code") +
  scale_y_reverse(expand = c(0.2, 0)) +
  theme_dendro()
 
```


cut the trees

https://uc-r.github.io/hc_clustering

```{r}


df_fviz_wss <- df_sak_corresp |> 
  fviz_nbclust(FUN = hcut, method = "wss", k.max = 30)

df_fviz_wss2 <- df_fviz_wss$data |> 
  mutate(clusters = as.numeric(clusters))
df_fviz_wss2 |>   
  ggplot(aes(clusters, y)) +
  geom_line() +
  # geom_point() +
  ylab("Total WSS") +
  xlab("No of clusters k") +
  theme_classic(base_family = "Fira Code")

  ggsave(filename = "output/sak_elbow.pdf", 
         device = cairo_pdf,
         dpi = 450,
         unit = "mm",
       height = 50, # pixelsでのサイズ
       width = 75,  # pixelsでのサイズ
       limitsize = FALSE)
```

```{r}
fviz_sil <- df_sak_corresp |> 
  fviz_nbclust(FUN = hcut, method = "silhouette", k.max = 30)
df_fviz_sil <- fviz_sil$data |> 
  mutate(clusters = as.numeric(clusters))
fviz_sil
df_fviz_sil |>   
  ggplot(aes(clusters, y)) +
  geom_line() +
  geom_vline(xintercept = 14, linetype = "dashed", colour = "gray90") +
  ylab("Avg sil width") +
  xlab("No of clusters k") +
  theme_classic(base_family = "Fira Code")

  ggsave(filename = "output/sak_sil.pdf", 
         device = cairo_pdf,
         dpi = 450,
         unit = "mm",
       height = 50, # pixelsでのサイズ
       width = 75,  # pixelsでのサイズ
       limitsize = FALSE)

```



